//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telegram_cloud.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Autorization_english {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Autorization_english() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Telegram_cloud.Resources.Autorization_english", typeof(Autorization_english).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press Enter.
        /// </summary>
        internal static string Auth_Email_Code_label_Content {
            get {
                return ResourceManager.GetString("Auth_Email_Code_label.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  .
        /// </summary>
        internal static string Auth_Email_Code_Text {
            get {
                return ResourceManager.GetString("Auth_Email_Code.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press Enter.
        /// </summary>
        internal static string Auth_Phone_Code_label_Content {
            get {
                return ResourceManager.GetString("Auth_Phone_Code_label.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  .
        /// </summary>
        internal static string Auth_Phone_Code_Text {
            get {
                return ResourceManager.GetString("Auth_Phone_Code.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press Enter.
        /// </summary>
        internal static string Email_Address_label_Content {
            get {
                return ResourceManager.GetString("Email_Address_label.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  .
        /// </summary>
        internal static string Email_Address_Text {
            get {
                return ResourceManager.GetString("Email_Address.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press Enter.
        /// </summary>
        internal static string Password_label_Content {
            get {
                return ResourceManager.GetString("Password_label.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  .
        /// </summary>
        internal static string Password_Text {
            get {
                return ResourceManager.GetString("Password.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press Enter.
        /// </summary>
        internal static string Phone_Number_label_Content {
            get {
                return ResourceManager.GetString("Phone_Number_label.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  .
        /// </summary>
        internal static string Phone_Number_Text {
            get {
                return ResourceManager.GetString("Phone_Number.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Enter a authentification code from email.
        /// </summary>
        internal static string TextBlock_Auth_Email_Code_background_Text {
            get {
                return ResourceManager.GetString("TextBlock_Auth_Email_Code_background.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Enter a authentification code from telegram.
        /// </summary>
        internal static string TextBlock_Auth_Phone_Code_background_Text {
            get {
                return ResourceManager.GetString("TextBlock_Auth_Phone_Code_background.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Enter a email address.
        /// </summary>
        internal static string TextBlock_Email_Address_background_Text {
            get {
                return ResourceManager.GetString("TextBlock_Email_Address_background.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Enter a password.
        /// </summary>
        internal static string TextBlock_Password_background_Text {
            get {
                return ResourceManager.GetString("TextBlock_Password_background.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Enter a phone number.
        /// </summary>
        internal static string TextBlock_phone_number_background_Text {
            get {
                return ResourceManager.GetString("TextBlock_phone_number_background.Text", resourceCulture);
            }
        }
    }
}
