//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telegram_cloud.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_english {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_english() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Telegram_cloud.Resources.Resource_english", typeof(Resource_english).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About account.
        /// </summary>
        internal static string About_account_Header {
            get {
                return ResourceManager.GetString("About_account.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About program.
        /// </summary>
        internal static string About_program_Header {
            get {
                return ResourceManager.GetString("About_program.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Detailed information about the program.
        /// </summary>
        internal static string About_program_ToolTip {
            get {
                return ResourceManager.GetString("About_program.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account.
        /// </summary>
        internal static string Account_Header {
            get {
                return ResourceManager.GetString("Account.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add drive from list.
        /// </summary>
        internal static string Add_drive_from_list_Header {
            get {
                return ResourceManager.GetString("Add_drive_from_list.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can add drive in telegram.org and add this channel in this app.
        /// </summary>
        internal static string Add_drive_from_list_ToolTip {
            get {
                return ResourceManager.GetString("Add_drive_from_list.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add drive.
        /// </summary>
        internal static string Add_drive_Header {
            get {
                return ResourceManager.GetString("Add_drive.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can add a channel in this app.
        /// </summary>
        internal static string Add_drive_ToolTip {
            get {
                return ResourceManager.GetString("Add_drive.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all image previews.
        /// </summary>
        internal static string Delete_All_Images_Preview_Header {
            get {
                return ResourceManager.GetString("Delete_All_Images_Preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all preview files for images from your computer.
        /// </summary>
        internal static string Delete_All_Images_Preview_ToolTip {
            get {
                return ResourceManager.GetString("Delete_All_Images_Preview.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all video preview.
        /// </summary>
        internal static string Delete_All_Videos_Preview_Header {
            get {
                return ResourceManager.GetString("Delete_All_Videos_Preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all preview files for a video from your computer.
        /// </summary>
        internal static string Delete_All_Videos_Preview_ToolTip {
            get {
                return ResourceManager.GetString("Delete_All_Videos_Preview.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download all drive.
        /// </summary>
        internal static string Download_all_drive_Header {
            get {
                return ResourceManager.GetString("Download_all_drive.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load the entire current drive on the PC.
        /// </summary>
        internal static string Download_all_drive_ToolTip {
            get {
                return ResourceManager.GetString("Download_all_drive.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download current directory.
        /// </summary>
        internal static string Download_current_directory_Header {
            get {
                return ResourceManager.GetString("Download_current_directory.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load the entire current directory on the PC.
        /// </summary>
        internal static string Download_current_directory_ToolTip {
            get {
                return ResourceManager.GetString("Download_current_directory.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatically download photo previews when you send them to drive.
        /// </summary>
        internal static string Download_photo_previews_automatically_ToolTip {
            get {
                return ResourceManager.GetString("Download_photo_previews_automatically.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatically download video previews when you send them to drive.
        /// </summary>
        internal static string Download_video_previews_automatically_ToolTip {
            get {
                return ResourceManager.GetString("Download_video_previews_automatically.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drives.
        /// </summary>
        internal static string Drives_list_Header {
            get {
                return ResourceManager.GetString("Drives_list.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Functions.
        /// </summary>
        internal static string Functions_Header {
            get {
                return ResourceManager.GetString("Functions.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download image preview from current directory.
        /// </summary>
        internal static string Load_Current_Directory_Image_Preview_Header {
            get {
                return ResourceManager.GetString("Load_Current_Directory_Image_Preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load all images from current directory in low quality.
        /// </summary>
        internal static string Load_Current_Directory_Image_Preview_ToolTip {
            get {
                return ResourceManager.GetString("Load_Current_Directory_Image_Preview.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download video preview from current directory.
        /// </summary>
        internal static string Load_Current_Directory_Video_Preview_Header {
            get {
                return ResourceManager.GetString("Load_Current_Directory_Video_Preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load all videos from current directory in low quality.
        /// </summary>
        internal static string Load_Current_Directory_Video_Preview_ToolTip {
            get {
                return ResourceManager.GetString("Load_Current_Directory_Video_Preview.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download preview of images.
        /// </summary>
        internal static string Load_Image_Preview_Header {
            get {
                return ResourceManager.GetString("Load_Image_Preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download all images in low quality.
        /// </summary>
        internal static string Load_Image_Preview_ToolTip {
            get {
                return ResourceManager.GetString("Load_Image_Preview.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download preview of videos.
        /// </summary>
        internal static string Load_Video_Preview_Header {
            get {
                return ResourceManager.GetString("Load_Video_Preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load all videos in low quality.
        /// </summary>
        internal static string Load_Video_Preview_ToolTip {
            get {
                return ResourceManager.GetString("Load_Video_Preview.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log out.
        /// </summary>
        internal static string Log_out_account_Header {
            get {
                return ResourceManager.GetString("Log_out_account.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You won&apos;t be able to log into that session, but it will stay in the telegram. To exit completely, in the telegram app, end the session with the signature &apos;Desktop TeleCloud 1.0 TDLib&apos;..
        /// </summary>
        internal static string Log_out_account_ToolTip {
            get {
                return ResourceManager.GetString("Log_out_account.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        internal static string Menu_autorize_Header {
            get {
                return ResourceManager.GetString("Menu_autorize.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load file.
        /// </summary>
        internal static string Menu_item_add_file_Header {
            get {
                return ResourceManager.GetString("Menu_item_add_file.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create directory.
        /// </summary>
        internal static string Menu_item_create_directory_Header {
            get {
                return ResourceManager.GetString("Menu_item_create_directory.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete a preview of file.
        /// </summary>
        internal static string Menu_item_delete_current_preview_Header {
            get {
                return ResourceManager.GetString("Menu_item_delete_current_preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string Menu_item_delete_Header {
            get {
                return ResourceManager.GetString("Menu_item_delete.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download a preview of file.
        /// </summary>
        internal static string Menu_item_download_current_preview_Header {
            get {
                return ResourceManager.GetString("Menu_item_download_current_preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download.
        /// </summary>
        internal static string Menu_item_download_Header {
            get {
                return ResourceManager.GetString("Menu_item_download.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move.
        /// </summary>
        internal static string Menu_item_move_Header {
            get {
                return ResourceManager.GetString("Menu_item_move.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pin message.
        /// </summary>
        internal static string Menu_item_pin_Header {
            get {
                return ResourceManager.GetString("Menu_item_pin.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename.
        /// </summary>
        internal static string Menu_item_rename_Header {
            get {
                return ResourceManager.GetString("Menu_item_rename.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unpin message.
        /// </summary>
        internal static string Menu_item_unpin_Header {
            get {
                return ResourceManager.GetString("Menu_item_unpin.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In progress.
        /// </summary>
        internal static string Progress_bar_ToolTip_In_progress {
            get {
                return ResourceManager.GetString("Progress_bar.ToolTip_In_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready.
        /// </summary>
        internal static string Progress_bar_ToolTip_Ready {
            get {
                return ResourceManager.GetString("Progress_bar.ToolTip_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string Settings_Header {
            get {
                return ResourceManager.GetString("Settings.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Languages.
        /// </summary>
        internal static string Settings_language_Header {
            get {
                return ResourceManager.GetString("Settings_language.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download photo previews automatically.
        /// </summary>
        internal static string Text_block_Download_photo_previews_automatically_Text {
            get {
                return ResourceManager.GetString("Text_block_Download_photo_previews_automatically.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download video previews automatically.
        /// </summary>
        internal static string Text_block_Download_video_previews_automatically_Text {
            get {
                return ResourceManager.GetString("Text_block_Download_video_previews_automatically.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complete.
        /// </summary>
        internal static string Text_complete_Text {
            get {
                return ResourceManager.GetString("Text_complete.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update drive.
        /// </summary>
        internal static string Update_current_drive_Header {
            get {
                return ResourceManager.GetString("Update_current_drive.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update all files in currwnt drive.
        /// </summary>
        internal static string Update_current_drive_ToolTip {
            get {
                return ResourceManager.GetString("Update_current_drive.ToolTip", resourceCulture);
            }
        }
    }
}
