//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telegram_cloud.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_russian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_russian() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Telegram_cloud.Resources.Resource_russian", typeof(Resource_russian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об аккаунте.
        /// </summary>
        internal static string About_account_Header {
            get {
                return ResourceManager.GetString("About_account.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        internal static string About_program_Header {
            get {
                return ResourceManager.GetString("About_program.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробная информация о программе.
        /// </summary>
        internal static string About_program_ToolTip {
            get {
                return ResourceManager.GetString("About_program.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт.
        /// </summary>
        internal static string Account_Header {
            get {
                return ResourceManager.GetString("Account.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить диск из списка.
        /// </summary>
        internal static string Add_drive_from_list_Header {
            get {
                return ResourceManager.GetString("Add_drive_from_list.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете добавить диск в telegram.org и добавить этот канал в этом приложении.
        /// </summary>
        internal static string Add_drive_from_list_ToolTip {
            get {
                return ResourceManager.GetString("Add_drive_from_list.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить диск.
        /// </summary>
        internal static string Add_drive_Header {
            get {
                return ResourceManager.GetString("Add_drive.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете добавить канал в этом приложении.
        /// </summary>
        internal static string Add_drive_ToolTip {
            get {
                return ResourceManager.GetString("Add_drive.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить весь предварительный просмотр изображений.
        /// </summary>
        internal static string Delete_All_Images_Preview_Header {
            get {
                return ResourceManager.GetString("Delete_All_Images_Preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить все файлы предварительного просмотра для изображений с компьютера.
        /// </summary>
        internal static string Delete_All_Images_Preview_ToolTip {
            get {
                return ResourceManager.GetString("Delete_All_Images_Preview.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить весь предварительный просмотр видео.
        /// </summary>
        internal static string Delete_All_Videos_Preview_Header {
            get {
                return ResourceManager.GetString("Delete_All_Videos_Preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить все файлы предварительного просмотра для видео с компьютера.
        /// </summary>
        internal static string Delete_All_Videos_Preview_ToolTip {
            get {
                return ResourceManager.GetString("Delete_All_Videos_Preview.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачать весь диск.
        /// </summary>
        internal static string Download_all_drive_Header {
            get {
                return ResourceManager.GetString("Download_all_drive.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить весь текущий диск на ПК.
        /// </summary>
        internal static string Download_all_drive_ToolTip {
            get {
                return ResourceManager.GetString("Download_all_drive.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить текущий каталог.
        /// </summary>
        internal static string Download_current_directory_Header {
            get {
                return ResourceManager.GetString("Download_current_directory.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить весь текущий каталог на ПК.
        /// </summary>
        internal static string Download_current_directory_ToolTip {
            get {
                return ResourceManager.GetString("Download_current_directory.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматически загружать предварительный просмотр фотографий при отправке их на диск.
        /// </summary>
        internal static string Download_photo_previews_automatically_ToolTip {
            get {
                return ResourceManager.GetString("Download_photo_previews_automatically.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматически загружать предварительный просмотр видео при отправке на диск.
        /// </summary>
        internal static string Download_video_previews_automatically_ToolTip {
            get {
                return ResourceManager.GetString("Download_video_previews_automatically.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диски.
        /// </summary>
        internal static string Drives_list_Header {
            get {
                return ResourceManager.GetString("Drives_list.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функции.
        /// </summary>
        internal static string Functions_Header {
            get {
                return ResourceManager.GetString("Functions.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить предпросмотр изображений из текущего каталога.
        /// </summary>
        internal static string Load_Current_Directory_Image_Preview_Header {
            get {
                return ResourceManager.GetString("Load_Current_Directory_Image_Preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить все изображения из текущего каталога в низком качестве.
        /// </summary>
        internal static string Load_Current_Directory_Image_Preview_ToolTip {
            get {
                return ResourceManager.GetString("Load_Current_Directory_Image_Preview.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить предпросмотр видео из текущей директории.
        /// </summary>
        internal static string Load_Current_Directory_Video_Preview_Header {
            get {
                return ResourceManager.GetString("Load_Current_Directory_Video_Preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить все видео из текущего каталога в низком качестве.
        /// </summary>
        internal static string Load_Current_Directory_Video_Preview_ToolTip {
            get {
                return ResourceManager.GetString("Load_Current_Directory_Video_Preview.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить предварительный просмотр изображений.
        /// </summary>
        internal static string Load_Image_Preview_Header {
            get {
                return ResourceManager.GetString("Load_Image_Preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузите все изображения в низком качестве.
        /// </summary>
        internal static string Load_Image_Preview_ToolTip {
            get {
                return ResourceManager.GetString("Load_Image_Preview.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить предварительный просмотр видео.
        /// </summary>
        internal static string Load_Video_Preview_Header {
            get {
                return ResourceManager.GetString("Load_Video_Preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузите все видео в низком качестве.
        /// </summary>
        internal static string Load_Video_Preview_ToolTip {
            get {
                return ResourceManager.GetString("Load_Video_Preview.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти из аккаунта.
        /// </summary>
        internal static string Log_out_account_Header {
            get {
                return ResourceManager.GetString("Log_out_account.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не сможете войти в эту сессию, но она останется в телеграмме. Чтобы выйти полностью, в приложении telegram завершите сеанс с подписью &apos;Desktop TeleCloud 1.0 TDLib&apos;..
        /// </summary>
        internal static string Log_out_account_ToolTip {
            get {
                return ResourceManager.GetString("Log_out_account.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизация.
        /// </summary>
        internal static string Menu_autorize_Header {
            get {
                return ResourceManager.GetString("Menu_autorize.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить файл.
        /// </summary>
        internal static string Menu_item_add_file_Header {
            get {
                return ResourceManager.GetString("Menu_item_add_file.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать каталог.
        /// </summary>
        internal static string Menu_item_create_directory_Header {
            get {
                return ResourceManager.GetString("Menu_item_create_directory.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить предварительный просмотр файла.
        /// </summary>
        internal static string Menu_item_delete_current_preview_Header {
            get {
                return ResourceManager.GetString("Menu_item_delete_current_preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string Menu_item_delete_Header {
            get {
                return ResourceManager.GetString("Menu_item_delete.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачать предварительный просмотр файла.
        /// </summary>
        internal static string Menu_item_download_current_preview_Header {
            get {
                return ResourceManager.GetString("Menu_item_download_current_preview.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачать.
        /// </summary>
        internal static string Menu_item_download_Header {
            get {
                return ResourceManager.GetString("Menu_item_download.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить.
        /// </summary>
        internal static string Menu_item_move_Header {
            get {
                return ResourceManager.GetString("Menu_item_move.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрепить сообщение.
        /// </summary>
        internal static string Menu_item_pin_Header {
            get {
                return ResourceManager.GetString("Menu_item_pin.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переименовать.
        /// </summary>
        internal static string Menu_item_rename_Header {
            get {
                return ResourceManager.GetString("Menu_item_rename.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открепить сообщение.
        /// </summary>
        internal static string Menu_item_unpin_Header {
            get {
                return ResourceManager.GetString("Menu_item_unpin.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В процессе.
        /// </summary>
        internal static string Progress_bar_ToolTip_In_progress {
            get {
                return ResourceManager.GetString("Progress_bar.ToolTip_In_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готово.
        /// </summary>
        internal static string Progress_bar_ToolTip_Ready {
            get {
                return ResourceManager.GetString("Progress_bar.ToolTip_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string Settings_Header {
            get {
                return ResourceManager.GetString("Settings.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Языки.
        /// </summary>
        internal static string Settings_language_Header {
            get {
                return ResourceManager.GetString("Settings_language.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматически загружать предварительный просмотр фотографий.
        /// </summary>
        internal static string Text_block_Download_photo_previews_automatically_Text {
            get {
                return ResourceManager.GetString("Text_block_Download_photo_previews_automatically.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматически загружать предварительный просмотр видео.
        /// </summary>
        internal static string Text_block_Download_video_previews_automatically_Text {
            get {
                return ResourceManager.GetString("Text_block_Download_video_previews_automatically.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершено.
        /// </summary>
        internal static string Text_complete_Text {
            get {
                return ResourceManager.GetString("Text_complete.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить диск.
        /// </summary>
        internal static string Update_current_drive_Header {
            get {
                return ResourceManager.GetString("Update_current_drive.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление всех файлов на текущем диске.
        /// </summary>
        internal static string Update_current_drive_ToolTip {
            get {
                return ResourceManager.GetString("Update_current_drive.ToolTip", resourceCulture);
            }
        }
    }
}
